apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    replicaCount: 2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - host: podinfo.${CLUSTER_URL}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - podinfo.${CLUSTER_URL}
          secretName: podinfo-tls
