replicaCount: 2
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: nginx
cert-manager.io/cluster-issuer: "letsencrypt-staging"
hosts:
- host: podinfo.${CLUSTER_URL}
  paths:
    - path: /
      pathType: ImplementationSpecific
tls:
- hosts:
    - podinfo.${CLUSTER_URL}
  secretName: podinfo-tls
