apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
  namespace: argocd
spec:
  project: perfana
  source:
    chart: mongodb
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.1.5
    helm:
      releaseName: mongodb
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: perfana
