architecture: replicaset
auth:
  enabled: true
  usernames: [perfana]
  databases: [perfana]
  existingSecret: mongo-credentials
replicaSetName: rs0
replicaSetHostnames: true
replicaCount: 3
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: "5.0"
  pullPolicy: IfNotPresent
persistence:
  enabled: true
  storageClass: hcloud-volumes
  size: 10Gi
